-- SECTION 1 - BASIC SELECT / FILTER / SORT

-- 1) List all customers with signup date, segment, and email domain extracted
SELECT
    FIRST_NAME,
    LAST_NAME,
    SIGNUP_DATE,
    SEGMENT,
    SPLIT_PART(EMAIL, '@', 2) AS EMAIL_DOMAIN
FROM DEMO_DW.SALES.DIM_CUSTOMER;

-- 2) Show all active products sorted by category and descending unit price
SELECT
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    UNIT_PRICE,
    ACTIVE
FROM DEMO_DW.SALES.DIM_PRODUCT
WHERE ACTIVE = TRUE
ORDER BY CATEGORY, UNIT_PRICE DESC;

-- 3) Find all promotions currently active
SELECT
    PROMO_ID,
    PROMO_TYPE,
    DISCOUNT_PCT,
    START_DATE,
    END_DATE
FROM DEMO_DW.SALES.DIM_PROMOTION
WHERE CURRENT_DATE BETWEEN START_DATE AND END_DATE;

-- 4) Find all stores in Alberta or Ontario regions
SELECT
    STORE_NAME,
    CITY,
    REGION
FROM DEMO_DW.SALES.DIM_STORE
WHERE REGION IN ('Alberta', 'Ontario');

-- 5) Show the first 10 days in DIM_DATE ordered by FULL_DATE
SELECT
    DATE_KEY,
    FULL_DATE,
    MONTH_NAME,
    YEAR
FROM DEMO_DW.SALES.DIM_DATE
ORDER BY FULL_DATE
LIMIT 10;

-- SECTION 2 - AGGREGATIONS AND KPIs

-- 6) Total revenue, total quantity, and average discount
SELECT
    SUM(REVENUE) AS TOTAL_REVENUE,
    SUM(QTY) AS TOTAL_QUANTITY,
    AVG(DISCOUNT_PCT) AS AVG_DISCOUNT
FROM DEMO_DW.SALES.V_SALES_ENRICHED;

-- 7) Average price per category and number of products per subcategory
SELECT
    CATEGORY,
    SUBCATEGORY,
    AVG(UNIT_PRICE) AS AVG_PRICE,
    COUNT(*) AS PRODUCT_COUNT
FROM DEMO_DW.SALES.DIM_PRODUCT
GROUP BY CATEGORY, SUBCATEGORY;

-- 8) Top 3 categories by total revenue
SELECT
    CATEGORY,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM DEMO_DW.SALES.V_SALES_ENRICHED
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

-- 9) Which promotion type generated the highest average revenue per order?
SELECT
    dp.PROMO_TYPE,
    AVG(fs.QTY * fs.UNIT_PRICE * (1 - fs.DISCOUNT_PCT)) AS AVG_REVENUE
FROM DEMO_DW.SALES.FACT_SALES fs
JOIN DEMO_DW.SALES.DIM_PROMOTION dp
    ON fs.PROMO_KEY = dp.PROMO_KEY
GROUP BY dp.PROMO_TYPE
ORDER BY AVG_REVENUE DESC
LIMIT 1;

-- 10) Show customers per segment sorted from most to least
SELECT
    SEGMENT,
    COUNT(*) AS CUSTOMER_COUNT
FROM DEMO_DW.SALES.DIM_CUSTOMER
GROUP BY SEGMENT
ORDER BY CUSTOMER_COUNT DESC;

-- SECTION 3 - JOINS PRACTICE

-- 1) Combine FACT_SALES, DIM_CUSTOMER, DIM_PRODUCT, DIM_STORE
--    Show customer name, product name, store name, revenue
SELECT
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    p.PRODUCT_NAME,
    s.STORE_NAME,
    fs.QTY * fs.UNIT_PRICE AS REVENUE
FROM DEMO_DW.SALES.FACT_SALES fs
JOIN DEMO_DW.SALES.DIM_CUSTOMER c
    ON fs.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DEMO_DW.SALES.DIM_PRODUCT p
    ON fs.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DEMO_DW.SALES.DIM_STORE s
    ON fs.STORE_KEY = s.STORE_KEY;

-- 2) Find customers who never purchased anything
SELECT
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL
FROM DEMO_DW.SALES.DIM_CUSTOMER c
LEFT JOIN DEMO_DW.SALES.FACT_SALES fs
    ON c.CUSTOMER_KEY = fs.CUSTOMER_KEY
WHERE fs.CUSTOMER_KEY IS NULL;

-- 3) Find products that were never sold
SELECT
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.UNIT_PRICE
FROM DEMO_DW.SALES.DIM_PRODUCT p
LEFT JOIN DEMO_DW.SALES.FACT_SALES fs
    ON p.PRODUCT_KEY = fs.PRODUCT_KEY
WHERE fs.PRODUCT_KEY IS NULL;

-- 4) Combine stores and customers using UNION with label column
SELECT
    STORE_NAME AS ENTITY_NAME,
    'Store' AS ENTITYTYPE
FROM DEMO_DW.SALES.DIM_STORE
UNION
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS ENTITY_NAME,
    'Customer' AS ENTITYTYPE
FROM DEMO_DW.SALES.DIM_CUSTOMER;

-- 5) For each store, show total sales and number of unique customers
SELECT
    s.STORE_NAME,
    SUM(fs.QTY * fs.UNIT_PRICE) AS TOTAL_SALES,
    COUNT(DISTINCT fs.CUSTOMER_KEY) AS UNIQUE_CUSTOMERS
FROM DEMO_DW.SALES.FACT_SALES fs
JOIN DEMO_DW.SALES.DIM_STORE s
    ON fs.STORE_KEY = s.STORE_KEY
GROUP BY s.STORE_NAME
ORDER BY TOTAL_SALES DESC;

-- SECTION 4 - CONDITIONAL LOGIC & FILTERING

-- 1) Add CASE column for revenue bands
SELECT
    PRODUCT_NAME,
    REVENUE,
    CASE
        WHEN REVENUE > 100 THEN 'High'
        WHEN REVENUE BETWEEN 50 AND 100 THEN 'Medium'
        ELSE 'Low'
    END AS REVENUE_LABEL
FROM DEMO_DW.SALES.V_SALES_ENRICHED;

-- 2) Find customers whose emails contain gmail.com
SELECT
    FIRST_NAME,
    LAST_NAME,
    EMAIL
FROM DEMO_DW.SALES.DIM_CUSTOMER
WHERE EMAIL LIKE '%gmail.com%';

-- 3) Show products whose name starts with S or ends with er
SELECT
    PRODUCT_NAME,
    UNIT_PRICE
FROM DEMO_DW.SALES.DIM_PRODUCT
WHERE PRODUCT_NAME LIKE 'S%'
   OR PRODUCT_NAME LIKE '%er';

-- 4) Subquery: products more expensive than average unit price
SELECT
    PRODUCT_NAME,
    UNIT_PRICE
FROM DEMO_DW.SALES.DIM_PRODUCT
WHERE UNIT_PRICE > (
    SELECT AVG(UNIT_PRICE)
    FROM DEMO_DW.SALES.DIM_PRODUCT);

-- 5) Show only customers with revenue above average
SELECT
    FIRST_NAME,
    LAST_NAME
FROM DEMO_DW.SALES.DIM_CUSTOMER
WHERE CUSTOMER_KEY IN (
    SELECT CUSTOMER_KEY
    FROM DEMO_DW.SALES.FACT_SALES
    GROUP BY CUSTOMER_KEY
    HAVING SUM(QTY * UNIT_PRICE) > (
        SELECT AVG(TOTAL_REVENUE)
        FROM (
            SELECT SUM(QTY * UNIT_PRICE) AS TOTAL_REVENUE
            FROM DEMO_DW.SALES.FACT_SALES
            GROUP BY CUSTOMER_KEY) t));

-- SECTION 5 - WINDOW FUNCTIONS

-- 1) Each customer’s total revenue and average order value
SELECT
    CUSTOMER_KEY,
    ORDER_ID,
    QTY * UNIT_PRICE AS REVENUE,
    SUM(QTY * UNIT_PRICE) OVER (PARTITION BY CUSTOMER_KEY) AS TOTAL_REVENUE_PER_CUSTOMER,
    AVG(QTY * UNIT_PRICE) OVER (PARTITION BY CUSTOMER_KEY) AS AVG_ORDER_VALUE_PER_CUSTOMER
FROM DEMO_DW.SALES.FACT_SALES;

-- 2) Ranking of products by revenue within category
SELECT
    CATEGORY,
    PRODUCT_NAME,
    SUM(REVENUE) AS TOTAL_REVENUE,
    RANK() OVER (
        PARTITION BY CATEGORY
        ORDER BY SUM(REVENUE) DESC
    ) AS REVENUE_RANK
FROM DEMO_DW.SALES.V_SALES_ENRICHED
GROUP BY CATEGORY, PRODUCT_NAME;

-- 3) Running total of daily revenue ordered by date
SELECT
    FULL_DATE,
    SUM(REVENUE) AS DAILY_REVENUE,
    SUM(SUM(REVENUE)) OVER (ORDER BY FULL_DATE) AS RUNNING_TOTAL_REVENUE
FROM DEMO_DW.SALES.V_SALES_ENRICHED
GROUP BY FULL_DATE
ORDER BY FULL_DATE;

-- 4) Show how much each sale differs from average
SELECT
    SALES_ID,
    REVENUE,
    REVENUE - AVG(REVENUE) OVER () AS DIFF_FROM_AVG
FROM DEMO_DW.SALES.V_SALES_ENRICHED;

-- 5) Find each customer’s first order
SELECT *
FROM (
    SELECT
        CUSTOMER_KEY,
        ORDER_ID,
        DATE_KEY,
        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_KEY
            ORDER BY DATE_KEY
        ) AS RN
    FROM DEMO_DW.SALES.FACT_SALES) t
WHERE RN = 1;

-- SECTION 6 - ADVANCED CHALLENGE

-- 1) Which 5 customers generated the most revenue?
SELECT
    c.FIRST_NAME,
    c.LAST_NAME,
    SUM(fs.QTY * fs.UNIT_PRICE) AS TOTAL_REVENUE
FROM DEMO_DW.SALES.FACT_SALES fs
JOIN DEMO_DW.SALES.DIM_CUSTOMER c
    ON fs.CUSTOMER_KEY = c.CUSTOMER_KEY
GROUP BY c.FIRST_NAME, c.LAST_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- 2) Which promotion type gave the biggest total discount amount?
SELECT
    dp.PROMO_TYPE,
    SUM(fs.QTY * fs.UNIT_PRICE * fs.DISCOUNT_PCT) AS TOTAL_DISCOUNT
FROM DEMO_DW.SALES.FACT_SALES fs
JOIN DEMO_DW.SALES.DIM_PROMOTION dp
    ON fs.PROMO_KEY = dp.PROMO_KEY
GROUP BY dp.PROMO_TYPE
ORDER BY TOTAL_DISCOUNT DESC
LIMIT 1;

-- 3) Which store and product pair generated the highest revenue?
SELECT
    STORE_NAME,
    PRODUCT_NAME,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM DEMO_DW.SALES.V_SALES_ENRICHED
GROUP BY STORE_NAME, PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- 4) Monthly total revenue trend
SELECT
    YEAR(d.FULL_DATE) AS YEAR_NUM,
    MONTH(d.FULL_DATE) AS MONTH_NUM,
    SUM(v.REVENUE) AS MONTHLY_REVENUE
FROM DEMO_DW.SALES.V_SALES_ENRICHED v
JOIN DEMO_DW.SALES.DIM_DATE d
    ON v.FULL_DATE = d.FULL_DATE
GROUP BY YEAR_NUM, MONTH_NUM
ORDER BY YEAR_NUM, MONTH_NUM;

-- 5) Find days where revenue dropped below the previous day
WITH daily_revenue AS (
    SELECT
        FULL_DATE,
        SUM(REVENUE) AS DAILY_REVENUE
    FROM DEMO_DW.SALES.V_SALES_ENRICHED
    GROUP BY FULL_DATE)
SELECT *
FROM (
    SELECT
        FULL_DATE,
        DAILY_REVENUE,
        LAG(DAILY_REVENUE) OVER (ORDER BY FULL_DATE) AS PREV_DAY_REVENUE
    FROM daily_revenue) t
WHERE PREV_DAY_REVENUE IS NOT NULL
  AND DAILY_REVENUE < PREV_DAY_REVENUE
ORDER BY FULL_DATE;